// GrowthLens - district-facing value-added interpretation tool
// Copyright (C) 2026 Andrew Camp
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.

// Forest plot data — coherent small district, generated by tools/build-demo.js.
window.GAPS_DATA = {
  meta: {
    subject: "math",
    demographic: "frl",
    groupA: "FRL",
    groupB: "non-FRL",
    districtGap: -0.1462,
    tauSquared: 0.0033,
    nSchools: 7,
    nMeetingThreshold: 6,
    minCellSize: 10,
  },
  schools: [
    { school_id: "Sch-1003", n_a: 150, n_b: 93, raw_gap: -0.2646, raw_se: 0.0671, raw_ci95: [-0.3961, -0.1331], shrunk_gap: -0.1965, shrunk_se: 0.0437, shrunk_ci95: [-0.2822, -0.1108], shrinkage_factor: 0.425, meets_min_cell: true },
    { school_id: "Sch-1001", n_a: 103, n_b: 141, raw_gap: -0.2187, raw_se: 0.0663, raw_ci95: [-0.3487, -0.0887], shrunk_gap: -0.1774, shrunk_se: 0.0435, shrunk_ci95: [-0.2627, -0.0921], shrinkage_factor: 0.43, meets_min_cell: true },
    { school_id: "Sch-1007", n_a: 216, n_b: 300, raw_gap: -0.1678, raw_se: 0.0425, raw_ci95: [-0.2511, -0.0845], shrunk_gap: -0.1602, shrunk_se: 0.0342, shrunk_ci95: [-0.2272, -0.0931], shrinkage_factor: 0.648, meets_min_cell: true },
    { school_id: "Sch-1005", n_a: 11, n_b: 8, raw_gap: -0.2774, raw_se: 0.1913, raw_ci95: [-0.6524, 0.0976], shrunk_gap: -0.1571, shrunk_se: 0.0552, shrunk_ci95: [-0.2653, -0.0489], shrinkage_factor: 0.083, meets_min_cell: false },
    { school_id: "Sch-1004", n_a: 130, n_b: 139, raw_gap: -0.1413, raw_se: 0.0604, raw_ci95: [-0.2597, -0.0229], shrunk_gap: -0.1439, shrunk_se: 0.0417, shrunk_ci95: [-0.2256, -0.0621], shrinkage_factor: 0.477, meets_min_cell: true },
    { school_id: "Sch-1002", n_a: 109, n_b: 161, raw_gap: -0.0755, raw_se: 0.0615, raw_ci95: [-0.196, 0.045], shrunk_gap: -0.1131, shrunk_se: 0.0421, shrunk_ci95: [-0.1955, -0.0307], shrinkage_factor: 0.468, meets_min_cell: true },
    { school_id: "Sch-1006", n_a: 222, n_b: 213, raw_gap: -0.0476, raw_se: 0.0461, raw_ci95: [-0.1379, 0.0427], shrunk_gap: -0.086, shrunk_se: 0.036, shrunk_ci95: [-0.1566, -0.0155], shrinkage_factor: 0.61, meets_min_cell: true },
  ],
};
