// GrowthLens - district-facing value-added interpretation tool
// Copyright (C) 2026 Andrew Camp
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.

// Forest plot data — all five DESE comparisons for the coherent small
// district, generated by tools/build-demo.js. The demo behaves exactly like
// an upload: every "Groups to compare" option is a real engine-computed slice.
window.GAPS_DATA_DEMO_ALL = {
  frl: {
    meta: {
      subject: "math",
      demographic: "frl",
      groupA: "FRL",
      groupB: "non-FRL",
      districtGap: -0.1342,
      districtCi95: [-0.2324, -0.0359],
      tauSquared: 0.0052,
      nSchools: 7,
      nMeetingThreshold: 6,
      minCellSize: 10,
    },
    schools: [
      { school_id: "Sch-1004", n_a: 137, n_b: 137, raw_gap: -0.2912, raw_se: 0.0588, raw_ci95: [-0.4066, -0.1759], shrunk_gap: -0.2287, shrunk_se: 0.0457, shrunk_ci95: [-0.3182, -0.1392], shrinkage_factor: 0.602, meets_min_cell: true },
      { school_id: "Sch-1003", n_a: 137, n_b: 91, raw_gap: -0.1937, raw_se: 0.0722, raw_ci95: [-0.3351, -0.0522], shrunk_gap: -0.164, shrunk_se: 0.0511, shrunk_ci95: [-0.2642, -0.0639], shrinkage_factor: 0.501, meets_min_cell: true },
      { school_id: "Sch-1001", n_a: 131, n_b: 121, raw_gap: -0.143, raw_se: 0.0609, raw_ci95: [-0.2624, -0.0236], shrunk_gap: -0.1393, shrunk_se: 0.0466, shrunk_ci95: [-0.2307, -0.048], shrinkage_factor: 0.585, meets_min_cell: true },
      { school_id: "Sch-1005", n_a: 15, n_b: 6, raw_gap: 0.2415, raw_se: 0.2608, raw_ci95: [-0.2696, 0.7526], shrunk_gap: -0.1073, shrunk_se: 0.0697, shrunk_ci95: [-0.244, 0.0294], shrinkage_factor: 0.072, meets_min_cell: false },
      { school_id: "Sch-1002", n_a: 87, n_b: 180, raw_gap: -0.0654, raw_se: 0.0706, raw_ci95: [-0.2037, 0.0729], shrunk_gap: -0.0989, shrunk_se: 0.0505, shrunk_ci95: [-0.1979, 0.0001], shrinkage_factor: 0.513, meets_min_cell: true },
      { school_id: "Sch-1006", n_a: 258, n_b: 201, raw_gap: -0.0738, raw_se: 0.0484, raw_ci95: [-0.1688, 0.0211], shrunk_gap: -0.0925, shrunk_se: 0.0402, shrunk_ci95: [-0.1714, -0.0136], shrinkage_factor: 0.691, meets_min_cell: true },
      { school_id: "Sch-1007", n_a: 194, n_b: 254, raw_gap: -0.0585, raw_se: 0.0479, raw_ci95: [-0.1524, 0.0355], shrunk_gap: -0.0815, shrunk_se: 0.04, shrunk_ci95: [-0.1599, -0.0032], shrinkage_factor: 0.695, meets_min_cell: true },
    ],
  },
  iep: {
    meta: {
      subject: "math",
      demographic: "iep",
      groupA: "IEP",
      groupB: "non-IEP",
      districtGap: -0.1837,
      districtCi95: [-0.2866, -0.0808],
      tauSquared: 0.0018,
      nSchools: 7,
      nMeetingThreshold: 6,
      minCellSize: 10,
    },
    schools: [
      { school_id: "Sch-1002", n_a: 31, n_b: 236, raw_gap: -0.3389, raw_se: 0.0895, raw_ci95: [-0.5142, -0.1635], shrunk_gap: -0.2125, shrunk_se: 0.0386, shrunk_ci95: [-0.2881, -0.1369], shrinkage_factor: 0.186, meets_min_cell: true },
      { school_id: "Sch-1006", n_a: 55, n_b: 404, raw_gap: -0.2521, raw_se: 0.0758, raw_ci95: [-0.4007, -0.1034], shrunk_gap: -0.2002, shrunk_se: 0.0372, shrunk_ci95: [-0.2731, -0.1272], shrinkage_factor: 0.241, meets_min_cell: true },
      { school_id: "Sch-1005", n_a: 3, n_b: 18, raw_gap: -0.5464, raw_se: 0.5465, raw_ci95: [-1.6175, 0.5247], shrunk_gap: -0.1859, shrunk_se: 0.0426, shrunk_ci95: [-0.2694, -0.1024], shrinkage_factor: 0.006, meets_min_cell: false },
      { school_id: "Sch-1001", n_a: 38, n_b: 214, raw_gap: -0.1436, raw_se: 0.099, raw_ci95: [-0.3377, 0.0505], shrunk_gap: -0.1774, shrunk_se: 0.0392, shrunk_ci95: [-0.2543, -0.1005], shrinkage_factor: 0.157, meets_min_cell: true },
      { school_id: "Sch-1007", n_a: 53, n_b: 395, raw_gap: -0.1563, raw_se: 0.0731, raw_ci95: [-0.2996, -0.0129], shrunk_gap: -0.1767, shrunk_se: 0.0369, shrunk_ci95: [-0.249, -0.1044], shrinkage_factor: 0.254, meets_min_cell: true },
      { school_id: "Sch-1004", n_a: 32, n_b: 242, raw_gap: -0.1015, raw_se: 0.0957, raw_ci95: [-0.289, 0.0861], shrunk_gap: -0.17, shrunk_se: 0.039, shrunk_ci95: [-0.2465, -0.0936], shrinkage_factor: 0.166, meets_min_cell: true },
      { school_id: "Sch-1003", n_a: 35, n_b: 193, raw_gap: -0.0474, raw_se: 0.1083, raw_ci95: [-0.2596, 0.1649], shrunk_gap: -0.1653, shrunk_se: 0.0397, shrunk_ci95: [-0.2432, -0.0874], shrinkage_factor: 0.135, meets_min_cell: true },
    ],
  },
  el: {
    meta: {
      subject: "math",
      demographic: "el",
      groupA: "EL",
      groupB: "non-EL",
      districtGap: -0.1544,
      districtCi95: [-0.2646, -0.0443],
      tauSquared: 0.0036,
      nSchools: 7,
      nMeetingThreshold: 6,
      minCellSize: 10,
    },
    schools: [
      { school_id: "Sch-1006", n_a: 57, n_b: 402, raw_gap: -0.2466, raw_se: 0.0644, raw_ci95: [-0.3729, -0.1202], shrunk_gap: -0.1972, shrunk_se: 0.0439, shrunk_ci95: [-0.2833, -0.1111], shrinkage_factor: 0.464, meets_min_cell: true },
      { school_id: "Sch-1001", n_a: 34, n_b: 218, raw_gap: -0.2527, raw_se: 0.0716, raw_ci95: [-0.3931, -0.1123], shrunk_gap: -0.195, shrunk_se: 0.046, shrunk_ci95: [-0.2851, -0.1048], shrinkage_factor: 0.412, meets_min_cell: true },
      { school_id: "Sch-1004", n_a: 28, n_b: 246, raw_gap: -0.1424, raw_se: 0.0889, raw_ci95: [-0.3166, 0.0318], shrunk_gap: -0.1506, shrunk_se: 0.0497, shrunk_ci95: [-0.2481, -0.0532], shrinkage_factor: 0.313, meets_min_cell: true },
      { school_id: "Sch-1003", n_a: 28, n_b: 200, raw_gap: -0.0741, raw_se: 0.1191, raw_ci95: [-0.3076, 0.1594], shrunk_gap: -0.1382, shrunk_se: 0.0536, shrunk_ci95: [-0.2432, -0.0331], shrinkage_factor: 0.202, meets_min_cell: true },
      { school_id: "Sch-1002", n_a: 22, n_b: 245, raw_gap: -0.0383, raw_se: 0.1085, raw_ci95: [-0.251, 0.1743], shrunk_gap: -0.1272, shrunk_se: 0.0525, shrunk_ci95: [-0.2302, -0.0243], shrinkage_factor: 0.234, meets_min_cell: true },
      { school_id: "Sch-1007", n_a: 42, n_b: 406, raw_gap: -0.0467, raw_se: 0.0845, raw_ci95: [-0.2124, 0.119], shrunk_gap: -0.1183, shrunk_se: 0.0489, shrunk_ci95: [-0.2142, -0.0224], shrinkage_factor: 0.335, meets_min_cell: true },
      { school_id: "Sch-1005", n_a: 0, n_b: 21, raw_gap: null, raw_se: null, raw_ci95: null, shrunk_gap: null, shrunk_se: null, shrunk_ci95: null, shrinkage_factor: null, meets_min_cell: false },
    ],
  },
  race_bw: {
    meta: {
      subject: "math",
      demographic: "race_bw",
      groupA: "Black",
      groupB: "White",
      districtGap: -0.2207,
      districtCi95: [-0.3391, -0.1023],
      tauSquared: 0.0033,
      nSchools: 7,
      nMeetingThreshold: 6,
      minCellSize: 10,
    },
    schools: [
      { school_id: "Sch-1004", n_a: 29, n_b: 189, raw_gap: -0.3428, raw_se: 0.0883, raw_ci95: [-0.5158, -0.1698], shrunk_gap: -0.2573, shrunk_se: 0.0483, shrunk_ci95: [-0.352, -0.1626], shrinkage_factor: 0.3, meets_min_cell: true },
      { school_id: "Sch-1005", n_a: 8, n_b: 8, raw_gap: -0.7994, raw_se: 0.2586, raw_ci95: [-1.3061, -0.2926], shrunk_gap: -0.2482, shrunk_se: 0.0564, shrunk_ci95: [-0.3587, -0.1377], shrinkage_factor: 0.048, meets_min_cell: false },
      { school_id: "Sch-1001", n_a: 17, n_b: 181, raw_gap: -0.3663, raw_se: 0.1396, raw_ci95: [-0.64, -0.0926], shrunk_gap: -0.242, shrunk_se: 0.0534, shrunk_ci95: [-0.3466, -0.1373], shrinkage_factor: 0.146, meets_min_cell: true },
      { school_id: "Sch-1003", n_a: 39, n_b: 151, raw_gap: -0.244, raw_se: 0.0944, raw_ci95: [-0.429, -0.0589], shrunk_gap: -0.227, shrunk_se: 0.0493, shrunk_ci95: [-0.3236, -0.1304], shrinkage_factor: 0.272, meets_min_cell: true },
      { school_id: "Sch-1007", n_a: 47, n_b: 331, raw_gap: -0.2011, raw_se: 0.0736, raw_ci95: [-0.3454, -0.0568], shrunk_gap: -0.2132, shrunk_se: 0.0454, shrunk_ci95: [-0.3023, -0.1241], shrinkage_factor: 0.381, meets_min_cell: true },
      { school_id: "Sch-1002", n_a: 10, n_b: 211, raw_gap: -0.1271, raw_se: 0.174, raw_ci95: [-0.4681, 0.2139], shrunk_gap: -0.2114, shrunk_se: 0.0548, shrunk_ci95: [-0.3188, -0.104], shrinkage_factor: 0.099, meets_min_cell: true },
      { school_id: "Sch-1006", n_a: 58, n_b: 312, raw_gap: -0.0939, raw_se: 0.0747, raw_ci95: [-0.2402, 0.0524], shrunk_gap: -0.1732, shrunk_se: 0.0457, shrunk_ci95: [-0.2628, -0.0837], shrinkage_factor: 0.374, meets_min_cell: true },
    ],
  },
  race_hw: {
    meta: {
      subject: "math",
      demographic: "race_hw",
      groupA: "Hispanic",
      groupB: "White",
      districtGap: -0.0746,
      districtCi95: [-0.1828, 0.0336],
      tauSquared: 0.0029,
      nSchools: 7,
      nMeetingThreshold: 6,
      minCellSize: 10,
    },
    schools: [
      { school_id: "Sch-1002", n_a: 30, n_b: 211, raw_gap: -0.223, raw_se: 0.0988, raw_ci95: [-0.4167, -0.0293], shrunk_gap: -0.1088, shrunk_se: 0.0474, shrunk_ci95: [-0.2017, -0.0158], shrinkage_factor: 0.23, meets_min_cell: true },
      { school_id: "Sch-1006", n_a: 52, n_b: 312, raw_gap: -0.1247, raw_se: 0.0708, raw_ci95: [-0.2636, 0.0141], shrunk_gap: -0.093, shrunk_se: 0.043, shrunk_ci95: [-0.1772, -0.0088], shrinkage_factor: 0.368, meets_min_cell: true },
      { school_id: "Sch-1007", n_a: 44, n_b: 331, raw_gap: -0.1072, raw_se: 0.0809, raw_ci95: [-0.2658, 0.0515], shrunk_gap: -0.0847, shrunk_se: 0.0449, shrunk_ci95: [-0.1727, 0.0034], shrinkage_factor: 0.308, meets_min_cell: true },
      { school_id: "Sch-1005", n_a: 3, n_b: 8, raw_gap: -0.3171, raw_se: 0.32, raw_ci95: [-0.9444, 0.3101], shrunk_gap: -0.0813, shrunk_se: 0.0533, shrunk_ci95: [-0.1858, 0.0231], shrinkage_factor: 0.028, meets_min_cell: false },
      { school_id: "Sch-1001", n_a: 33, n_b: 181, raw_gap: -0.0772, raw_se: 0.092, raw_ci95: [-0.2575, 0.103], shrunk_gap: -0.0753, shrunk_se: 0.0466, shrunk_ci95: [-0.1666, 0.016], shrinkage_factor: 0.257, meets_min_cell: true },
      { school_id: "Sch-1004", n_a: 37, n_b: 189, raw_gap: -0.0168, raw_se: 0.0795, raw_ci95: [-0.1726, 0.1389], shrunk_gap: -0.0563, shrunk_se: 0.0447, shrunk_ci95: [-0.1439, 0.0312], shrinkage_factor: 0.316, meets_min_cell: true },
      { school_id: "Sch-1003", n_a: 21, n_b: 151, raw_gap: 0.1914, raw_se: 0.1197, raw_ci95: [-0.0433, 0.4261], shrunk_gap: -0.0296, shrunk_se: 0.0492, shrunk_ci95: [-0.1261, 0.0669], shrinkage_factor: 0.169, meets_min_cell: true },
    ],
  },
};
window.GAPS_DATA = window.GAPS_DATA_DEMO_ALL.frl;
