// GrowthLens - district-facing value-added interpretation tool
// Copyright (C) 2026 Andrew Camp
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.

// Heatmap data — school × grade residuals, generated by tools/build-demo.js.
window.HEATMAP_DATA = {"meta":{"subject":"math"},"schools":[{"school_id":"Sch-1001","grades":{"3":{"n":89,"r":-0.283,"rs":-0.269,"ok":true},"4":{"n":83,"r":-0.19,"rs":-0.174,"ok":true},"5":{"n":80,"r":-0.197,"rs":-0.174,"ok":true}},"overall":{"n":252,"r":-0.225,"rs":-0.219}},{"school_id":"Sch-1002","grades":{"3":{"n":90,"r":0.111,"rs":0.101,"ok":true},"4":{"n":83,"r":0.16,"rs":0.143,"ok":true},"5":{"n":94,"r":0.003,"rs":-0.011,"ok":true}},"overall":{"n":267,"r":0.088,"rs":0.082}},{"school_id":"Sch-1003","grades":{"3":{"n":81,"r":-0.055,"rs":-0.051,"ok":true},"4":{"n":74,"r":-0.222,"rs":-0.203,"ok":true},"5":{"n":73,"r":-0.122,"rs":-0.108,"ok":true}},"overall":{"n":228,"r":-0.131,"rs":-0.127}},{"school_id":"Sch-1004","grades":{"3":{"n":92,"r":0.158,"rs":0.146,"ok":true},"4":{"n":92,"r":0.082,"rs":0.073,"ok":true},"5":{"n":90,"r":0.082,"rs":0.055,"ok":true}},"overall":{"n":274,"r":0.107,"rs":0.101}},{"school_id":"Sch-1005","grades":{"3":{"n":7,"r":-0.424,"rs":-0.214,"ok":false},"4":{"n":7,"r":-0.319,"rs":-0.198,"ok":false},"5":{"n":7,"r":-0.455,"rs":-0.099,"ok":false}},"overall":{"n":21,"r":-0.399,"rs":-0.255}},{"school_id":"Sch-1006","grades":{"6":{"n":139,"r":-0.007,"rs":0.004,"ok":true},"7":{"n":154,"r":-0.157,"rs":-0.146,"ok":true},"8":{"n":166,"r":-0.112,"rs":-0.103,"ok":true}},"overall":{"n":459,"r":-0.095,"rs":-0.094}},{"school_id":"Sch-1007","grades":{"6":{"n":144,"r":0.153,"rs":0.14,"ok":true},"7":{"n":161,"r":0.015,"rs":0.007,"ok":true},"8":{"n":143,"r":0.083,"rs":0.073,"ok":true}},"overall":{"n":448,"r":0.081,"rs":0.078}}]};
