// GrowthLens - district-facing value-added interpretation tool
// Copyright (C) 2026 Andrew Camp
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.

// Heatmap data — school × grade residuals, generated by tools/build-demo.js.
window.HEATMAP_DATA = {"meta":{"subject":"math"},"schools":[{"school_id":"Sch-1001","grades":{"3":{"n":89,"r":-0.283,"ok":true},"4":{"n":83,"r":-0.19,"ok":true},"5":{"n":80,"r":-0.197,"ok":true}}},{"school_id":"Sch-1002","grades":{"3":{"n":90,"r":0.111,"ok":true},"4":{"n":83,"r":0.16,"ok":true},"5":{"n":94,"r":0.003,"ok":true}}},{"school_id":"Sch-1003","grades":{"3":{"n":81,"r":-0.055,"ok":true},"4":{"n":74,"r":-0.222,"ok":true},"5":{"n":73,"r":-0.122,"ok":true}}},{"school_id":"Sch-1004","grades":{"3":{"n":92,"r":0.158,"ok":true},"4":{"n":92,"r":0.082,"ok":true},"5":{"n":90,"r":0.082,"ok":true}}},{"school_id":"Sch-1005","grades":{"3":{"n":7,"r":-0.424,"ok":false},"4":{"n":7,"r":-0.319,"ok":false},"5":{"n":7,"r":-0.455,"ok":false}}},{"school_id":"Sch-1006","grades":{"6":{"n":139,"r":-0.007,"ok":true},"7":{"n":154,"r":-0.157,"ok":true},"8":{"n":166,"r":-0.112,"ok":true}}},{"school_id":"Sch-1007","grades":{"6":{"n":144,"r":0.153,"ok":true},"7":{"n":161,"r":0.015,"ok":true},"8":{"n":143,"r":0.083,"ok":true}}}]};
